
//input ports
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point clk_test clk_test -type PI PI
add mapped point TM TM -type PI PI

//output ports
add mapped point out out -type PO PO

//inout ports




//Sequential Pins
add mapped point count[0]/q count_reg[0]/Q -type DFF DFF
add mapped point count[1]/q count_reg[1]/Q -type DFF DFF
add mapped point count[2]/q count_reg[2]/Q -type DFF DFF
add mapped point count[3]/q count_reg[3]/Q -type DFF DFF
add mapped point count[4]/q count_reg[4]/Q -type DFF DFF
add mapped point count[5]/q count_reg[5]/Q -type DFF DFF
add mapped point count[6]/q count_reg[6]/Q -type DFF DFF
add mapped point count[7]/q count_reg[7]/Q -type DFF DFF
add mapped point count[8]/q count_reg[8]/Q -type DFF DFF
add mapped point count[9]/q count_reg[9]/Q -type DFF DFF
add mapped point count[10]/q count_reg[10]/Q -type DFF DFF
add mapped point count[11]/q count_reg[11]/Q -type DFF DFF
add mapped point count[12]/q count_reg[12]/Q -type DFF DFF
add mapped point count[13]/q count_reg[13]/Q -type DFF DFF
add mapped point count[14]/q count_reg[14]/Q -type DFF DFF
add mapped point count[15]/q count_reg[15]/Q -type DFF DFF
add mapped point count[16]/q count_reg[16]/Q -type DFF DFF
add mapped point count[17]/q count_reg[17]/Q -type DFF DFF
add mapped point count[18]/q count_reg[18]/Q -type DFF DFF
add mapped point count[19]/q count_reg[19]/Q -type DFF DFF
add mapped point count[20]/q count_reg[20]/Q -type DFF DFF
add mapped point count[21]/q count_reg[21]/Q -type DFF DFF
add mapped point count[22]/q count_reg[22]/Q -type DFF DFF
add mapped point count[23]/q count_reg[23]/Q -type DFF DFF
add mapped point count[24]/q count_reg[24]/Q -type DFF DFF
add mapped point count[25]/q count_reg[25]/Q -type DFF DFF
add mapped point count[26]/q count_reg[26]/Q -type DFF DFF
add mapped point count[27]/q count_reg[27]/Q -type DFF DFF
add mapped point count[28]/q count_reg[28]/Q -type DFF DFF
add mapped point count[29]/q count_reg[29]/Q -type DFF DFF
add mapped point count[30]/q count_reg[30]/Q -type DFF DFF
add mapped point count[31]/q count_reg[31]/Q -type DFF DFF
add mapped point count[32]/q count_reg[32]/Q -type DFF DFF
add mapped point count[33]/q count_reg[33]/Q -type DFF DFF
add mapped point count[34]/q count_reg[34]/Q -type DFF DFF
add mapped point count[35]/q count_reg[35]/Q -type DFF DFF
add mapped point count[36]/q count_reg[36]/Q -type DFF DFF
add mapped point count[37]/q count_reg[37]/Q -type DFF DFF
add mapped point count[38]/q count_reg[38]/Q -type DFF DFF
add mapped point count[39]/q count_reg[39]/Q -type DFF DFF
add mapped point count[40]/q count_reg[40]/Q -type DFF DFF
add mapped point count[41]/q count_reg[41]/Q -type DFF DFF
add mapped point count[42]/q count_reg[42]/Q -type DFF DFF
add mapped point count[43]/q count_reg[43]/Q -type DFF DFF
add mapped point count[44]/q count_reg[44]/Q -type DFF DFF
add mapped point count[45]/q count_reg[45]/Q -type DFF DFF
add mapped point count[46]/q count_reg[46]/Q -type DFF DFF
add mapped point count[47]/q count_reg[47]/Q -type DFF DFF
add mapped point count[48]/q count_reg[48]/Q -type DFF DFF
add mapped point count[49]/q count_reg[49]/Q -type DFF DFF
add mapped point count[50]/q count_reg[50]/Q -type DFF DFF
add mapped point count[51]/q count_reg[51]/Q -type DFF DFF
add mapped point count[52]/q count_reg[52]/Q -type DFF DFF
add mapped point count[53]/q count_reg[53]/Q -type DFF DFF
add mapped point count[54]/q count_reg[54]/Q -type DFF DFF
add mapped point count[55]/q count_reg[55]/Q -type DFF DFF
add mapped point count[56]/q count_reg[56]/Q -type DFF DFF
add mapped point count[57]/q count_reg[57]/Q -type DFF DFF
add mapped point count[58]/q count_reg[58]/Q -type DFF DFF
add mapped point count[59]/q count_reg[59]/Q -type DFF DFF
add mapped point count[60]/q count_reg[60]/Q -type DFF DFF
add mapped point count[61]/q count_reg[61]/Q -type DFF DFF
add mapped point count[62]/q count_reg[62]/Q -type DFF DFF
add mapped point count[63]/q count_reg[63]/Q -type DFF DFF
add mapped point count[64]/q count_reg[64]/Q -type DFF DFF
add mapped point count[65]/q count_reg[65]/Q -type DFF DFF
add mapped point count[66]/q count_reg[66]/Q -type DFF DFF
add mapped point count[67]/q count_reg[67]/Q -type DFF DFF
add mapped point count[68]/q count_reg[68]/Q -type DFF DFF
add mapped point count[69]/q count_reg[69]/Q -type DFF DFF
add mapped point count[70]/q count_reg[70]/Q -type DFF DFF
add mapped point count[71]/q count_reg[71]/Q -type DFF DFF
add mapped point count[72]/q count_reg[72]/Q -type DFF DFF
add mapped point count[73]/q count_reg[73]/Q -type DFF DFF
add mapped point count[74]/q count_reg[74]/Q -type DFF DFF
add mapped point count[75]/q count_reg[75]/Q -type DFF DFF
add mapped point count[76]/q count_reg[76]/Q -type DFF DFF
add mapped point count[77]/q count_reg[77]/Q -type DFF DFF
add mapped point count[78]/q count_reg[78]/Q -type DFF DFF
add mapped point count[79]/q count_reg[79]/Q -type DFF DFF
add mapped point count[80]/q count_reg[80]/Q -type DFF DFF
add mapped point count[81]/q count_reg[81]/Q -type DFF DFF
add mapped point count[82]/q count_reg[82]/Q -type DFF DFF
add mapped point count[83]/q count_reg[83]/Q -type DFF DFF
add mapped point count[84]/q count_reg[84]/Q -type DFF DFF
add mapped point count[85]/q count_reg[85]/Q -type DFF DFF
add mapped point count[86]/q count_reg[86]/Q -type DFF DFF
add mapped point count[87]/q count_reg[87]/Q -type DFF DFF
add mapped point count[88]/q count_reg[88]/Q -type DFF DFF
add mapped point count[89]/q count_reg[89]/Q -type DFF DFF
add mapped point count[90]/q count_reg[90]/Q -type DFF DFF
add mapped point count[91]/q count_reg[91]/Q -type DFF DFF
add mapped point count[92]/q count_reg[92]/Q -type DFF DFF
add mapped point count[93]/q count_reg[93]/Q -type DFF DFF
add mapped point count[94]/q count_reg[94]/Q -type DFF DFF
add mapped point count[95]/q count_reg[95]/Q -type DFF DFF
add mapped point count[96]/q count_reg[96]/Q -type DFF DFF
add mapped point count[97]/q count_reg[97]/Q -type DFF DFF
add mapped point count[98]/q count_reg[98]/Q -type DFF DFF
add mapped point count[99]/q count_reg[99]/Q -type DFF DFF
add mapped point count[100]/q count_reg[100]/Q -type DFF DFF
add mapped point count[101]/q count_reg[101]/Q -type DFF DFF
add mapped point count[102]/q count_reg[102]/Q -type DFF DFF
add mapped point count[103]/q count_reg[103]/Q -type DFF DFF
add mapped point count[104]/q count_reg[104]/Q -type DFF DFF
add mapped point count[105]/q count_reg[105]/Q -type DFF DFF
add mapped point count[106]/q count_reg[106]/Q -type DFF DFF
add mapped point count[107]/q count_reg[107]/Q -type DFF DFF
add mapped point count[108]/q count_reg[108]/Q -type DFF DFF
add mapped point count[109]/q count_reg[109]/Q -type DFF DFF
add mapped point count[110]/q count_reg[110]/Q -type DFF DFF
add mapped point count[111]/q count_reg[111]/Q -type DFF DFF
add mapped point count[112]/q count_reg[112]/Q -type DFF DFF
add mapped point count[113]/q count_reg[113]/Q -type DFF DFF
add mapped point count[114]/q count_reg[114]/Q -type DFF DFF
add mapped point count[115]/q count_reg[115]/Q -type DFF DFF
add mapped point count[116]/q count_reg[116]/Q -type DFF DFF
add mapped point count[117]/q count_reg[117]/Q -type DFF DFF
add mapped point count[118]/q count_reg[118]/Q -type DFF DFF
add mapped point count[119]/q count_reg[119]/Q -type DFF DFF
add mapped point count[120]/q count_reg[120]/Q -type DFF DFF
add mapped point count[121]/q count_reg[121]/Q -type DFF DFF
add mapped point count[122]/q count_reg[122]/Q -type DFF DFF
add mapped point count[123]/q count_reg[123]/Q -type DFF DFF
add mapped point count[124]/q count_reg[124]/Q -type DFF DFF
add mapped point count[125]/q count_reg[125]/Q -type DFF DFF
add mapped point count[126]/q count_reg[126]/Q -type DFF DFF
add mapped point count[127]/q count_reg[127]/Q -type DFF DFF
add mapped point count[128]/q count_reg[128]/Q -type DFF DFF
add mapped point count[129]/q count_reg[129]/Q -type DFF DFF
add mapped point count[130]/q count_reg[130]/Q -type DFF DFF
add mapped point count[131]/q count_reg[131]/Q -type DFF DFF
add mapped point count[132]/q count_reg[132]/Q -type DFF DFF
add mapped point count[133]/q count_reg[133]/Q -type DFF DFF
add mapped point count[134]/q count_reg[134]/Q -type DFF DFF
add mapped point count[135]/q count_reg[135]/Q -type DFF DFF
add mapped point count[136]/q count_reg[136]/Q -type DFF DFF
add mapped point count[137]/q count_reg[137]/Q -type DFF DFF
add mapped point count[138]/q count_reg[138]/Q -type DFF DFF
add mapped point count[139]/q count_reg[139]/Q -type DFF DFF
add mapped point count[140]/q count_reg[140]/Q -type DFF DFF
add mapped point count[141]/q count_reg[141]/Q -type DFF DFF
add mapped point count[142]/q count_reg[142]/Q -type DFF DFF
add mapped point count[143]/q count_reg[143]/Q -type DFF DFF
add mapped point count[144]/q count_reg[144]/Q -type DFF DFF
add mapped point count[145]/q count_reg[145]/Q -type DFF DFF
add mapped point count[146]/q count_reg[146]/Q -type DFF DFF
add mapped point count[147]/q count_reg[147]/Q -type DFF DFF
add mapped point count[148]/q count_reg[148]/Q -type DFF DFF
add mapped point count[149]/q count_reg[149]/Q -type DFF DFF
add mapped point count[150]/q count_reg[150]/Q -type DFF DFF
add mapped point count[151]/q count_reg[151]/Q -type DFF DFF
add mapped point count[152]/q count_reg[152]/Q -type DFF DFF
add mapped point count[153]/q count_reg[153]/Q -type DFF DFF
add mapped point count[154]/q count_reg[154]/Q -type DFF DFF
add mapped point count[155]/q count_reg[155]/Q -type DFF DFF
add mapped point count[156]/q count_reg[156]/Q -type DFF DFF
add mapped point count[157]/q count_reg[157]/Q -type DFF DFF
add mapped point count[158]/q count_reg[158]/Q -type DFF DFF
add mapped point count[159]/q count_reg[159]/Q -type DFF DFF
add mapped point count[160]/q count_reg[160]/Q -type DFF DFF
add mapped point count[161]/q count_reg[161]/Q -type DFF DFF
add mapped point count[162]/q count_reg[162]/Q -type DFF DFF
add mapped point count[163]/q count_reg[163]/Q -type DFF DFF
add mapped point count[164]/q count_reg[164]/Q -type DFF DFF
add mapped point count[165]/q count_reg[165]/Q -type DFF DFF
add mapped point count[166]/q count_reg[166]/Q -type DFF DFF
add mapped point count[167]/q count_reg[167]/Q -type DFF DFF
add mapped point count[168]/q count_reg[168]/Q -type DFF DFF
add mapped point count[169]/q count_reg[169]/Q -type DFF DFF
add mapped point count[170]/q count_reg[170]/Q -type DFF DFF
add mapped point count[171]/q count_reg[171]/Q -type DFF DFF
add mapped point count[172]/q count_reg[172]/Q -type DFF DFF
add mapped point count[173]/q count_reg[173]/Q -type DFF DFF
add mapped point count[174]/q count_reg[174]/Q -type DFF DFF
add mapped point count[175]/q count_reg[175]/Q -type DFF DFF
add mapped point count[176]/q count_reg[176]/Q -type DFF DFF
add mapped point count[177]/q count_reg[177]/Q -type DFF DFF
add mapped point count[178]/q count_reg[178]/Q -type DFF DFF
add mapped point count[179]/q count_reg[179]/Q -type DFF DFF
add mapped point count[180]/q count_reg[180]/Q -type DFF DFF
add mapped point count[181]/q count_reg[181]/Q -type DFF DFF
add mapped point count[182]/q count_reg[182]/Q -type DFF DFF
add mapped point count[183]/q count_reg[183]/Q -type DFF DFF
add mapped point count[184]/q count_reg[184]/Q -type DFF DFF
add mapped point count[185]/q count_reg[185]/Q -type DFF DFF
add mapped point count[186]/q count_reg[186]/Q -type DFF DFF
add mapped point count[187]/q count_reg[187]/Q -type DFF DFF
add mapped point count[188]/q count_reg[188]/Q -type DFF DFF
add mapped point count[189]/q count_reg[189]/Q -type DFF DFF
add mapped point count[190]/q count_reg[190]/Q -type DFF DFF
add mapped point count[191]/q count_reg[191]/Q -type DFF DFF
add mapped point count[192]/q count_reg[192]/Q -type DFF DFF
add mapped point count[193]/q count_reg[193]/Q -type DFF DFF
add mapped point count[194]/q count_reg[194]/Q -type DFF DFF
add mapped point count[195]/q count_reg[195]/Q -type DFF DFF
add mapped point count[196]/q count_reg[196]/Q -type DFF DFF
add mapped point count[197]/q count_reg[197]/Q -type DFF DFF
add mapped point count[198]/q count_reg[198]/Q -type DFF DFF
add mapped point count[199]/q count_reg[199]/Q -type DFF DFF
add mapped point count[200]/q count_reg[200]/Q -type DFF DFF
add mapped point count[201]/q count_reg[201]/Q -type DFF DFF
add mapped point count[202]/q count_reg[202]/Q -type DFF DFF
add mapped point count[203]/q count_reg[203]/Q -type DFF DFF
add mapped point count[204]/q count_reg[204]/Q -type DFF DFF
add mapped point count[205]/q count_reg[205]/Q -type DFF DFF
add mapped point count[206]/q count_reg[206]/Q -type DFF DFF
add mapped point count[207]/q count_reg[207]/Q -type DFF DFF
add mapped point count[208]/q count_reg[208]/Q -type DFF DFF
add mapped point count[209]/q count_reg[209]/Q -type DFF DFF
add mapped point count[210]/q count_reg[210]/Q -type DFF DFF
add mapped point count[211]/q count_reg[211]/Q -type DFF DFF
add mapped point count[212]/q count_reg[212]/Q -type DFF DFF
add mapped point count[213]/q count_reg[213]/Q -type DFF DFF
add mapped point count[214]/q count_reg[214]/Q -type DFF DFF
add mapped point count[215]/q count_reg[215]/Q -type DFF DFF
add mapped point count[216]/q count_reg[216]/Q -type DFF DFF
add mapped point count[217]/q count_reg[217]/Q -type DFF DFF
add mapped point count[218]/q count_reg[218]/Q -type DFF DFF
add mapped point count[219]/q count_reg[219]/Q -type DFF DFF
add mapped point count[220]/q count_reg[220]/Q -type DFF DFF
add mapped point count[221]/q count_reg[221]/Q -type DFF DFF
add mapped point count[222]/q count_reg[222]/Q -type DFF DFF
add mapped point count[223]/q count_reg[223]/Q -type DFF DFF
add mapped point count[224]/q count_reg[224]/Q -type DFF DFF
add mapped point count[225]/q count_reg[225]/Q -type DFF DFF
add mapped point count[226]/q count_reg[226]/Q -type DFF DFF
add mapped point count[227]/q count_reg[227]/Q -type DFF DFF
add mapped point count[228]/q count_reg[228]/Q -type DFF DFF
add mapped point count[229]/q count_reg[229]/Q -type DFF DFF
add mapped point count[230]/q count_reg[230]/Q -type DFF DFF
add mapped point count[231]/q count_reg[231]/Q -type DFF DFF
add mapped point count[232]/q count_reg[232]/Q -type DFF DFF
add mapped point count[233]/q count_reg[233]/Q -type DFF DFF
add mapped point count[234]/q count_reg[234]/Q -type DFF DFF
add mapped point count[235]/q count_reg[235]/Q -type DFF DFF
add mapped point count[236]/q count_reg[236]/Q -type DFF DFF
add mapped point count[237]/q count_reg[237]/Q -type DFF DFF
add mapped point count[238]/q count_reg[238]/Q -type DFF DFF
add mapped point count[239]/q count_reg[239]/Q -type DFF DFF
add mapped point count[240]/q count_reg[240]/Q -type DFF DFF
add mapped point count[241]/q count_reg[241]/Q -type DFF DFF
add mapped point count[242]/q count_reg[242]/Q -type DFF DFF
add mapped point count[243]/q count_reg[243]/Q -type DFF DFF
add mapped point count[244]/q count_reg[244]/Q -type DFF DFF
add mapped point count[245]/q count_reg[245]/Q -type DFF DFF
add mapped point count[246]/q count_reg[246]/Q -type DFF DFF
add mapped point count[247]/q count_reg[247]/Q -type DFF DFF
add mapped point count[248]/q count_reg[248]/Q -type DFF DFF
add mapped point count[249]/q count_reg[249]/Q -type DFF DFF
add mapped point count[250]/q count_reg[250]/Q -type DFF DFF
add mapped point count[251]/q count_reg[251]/Q -type DFF DFF
add mapped point count[252]/q count_reg[252]/Q -type DFF DFF
add mapped point count[253]/q count_reg[253]/Q -type DFF DFF
add mapped point count[254]/q count_reg[254]/Q -type DFF DFF
add mapped point count[255]/q count_reg[255]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
